language: ruby
cache: bundler
rvm:
  - 2.5.3 # deployed
  - 2.7.1

before_install:
  - gem update --system
  - npm install -g openapi-enforcer-cli

script:
  - ./validate-openapi.bash || travis_terminate 1
  - bundle exec rubocop
  - bundle exec rspec
