version: 2.1
orbs:
  ruby-rails: sul-dlss/ruby-rails@3.1.2
workflows:
  build:
    jobs:
      - ruby-rails/validate-api:
          name: validate
      - ruby-rails/lint:
          name: lint
      # Using test-gem since no DB.    
      - ruby-rails/test-gem:
          name: test
      - ruby-rails/docker-publish:
          context: dlss
          name: publish-latest
          image: suldlss/dor-indexing-app
          requires:
            - validate
            - lint
            - test
          filters:
            branches:
              only:
                - main
