version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      # - run:
      #     name: Install API enforcer
      #     command: npm install -g openapi-enforcer-cli
      - run:
          name: Install latest bundler
          command: gem install bundler
      - run:
          name: Config bundler
          command: bundle config set without 'production'
      - run:
          name: Install gems
          command: bundle install
      - run:
          name: Set up CodeClimate
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter before-build
      # - run:
      #     name: Validate API
      #     command: ./validate-openapi.bash
      - run:
          name: Run linter
          command: bundle exec rubocop
      - run:
          name: Run tests
          command: RAILS_ENV=test bundle exec rake spec
      - run:
          name: Report test coverage results to CodeClimate
          command: ./cc-test-reporter after-build --coverage-input-type simplecov --exit-code $?
