version: 2.1
orbs:
  ruby-rails: sul-dlss/ruby-rails@3.2.0
workflows:
  build:
    jobs:
      - ruby-rails/validate-api:
          name: validate
      - ruby-rails/lint:
          name: lint
          executor:
            name: ruby-rails/ruby
            ruby-tag: '3.2.2'
      # Using test-gem since no DB.
      - ruby-rails/test-gem:
          name: test
          executor:
            name: ruby-rails/ruby
            ruby-tag: '3.2.2'
      - ruby-rails/docker-publish:
          context: dlss
          name: publish-latest
          image: suldlss/dor-indexing-app
          requires:
            - validate
            - lint
            - test
          filters:
            branches:
              only:
                - main
