# General
date_format_str: '%Y-%m-%d %H:%M:%S.%L'
rolling_indexer:
  processes: 2
  batch_size: 500
  pause_time_between_batches: 5 # This is a wild guess. We can turn this up/down as necessary.

ssl:
  cert_file: ~
  key_file: ~
  key_pass: ~

workflow:
  logfile: 'log/workflow_service.log'
  shift_age: 'weekly'
  timeout: 60

fedora_url: 'https://user:password@fedora.example.com:1000/fedora'
solrizer_url: 'https://solr.example.com/solr/collection'
workflow_url: 'https://workflow.example.edu/'

dor_services:
  url: 'http://localhost:3003'
  token: 'not-a-real-token'

rabbitmq:
  hostname: localhost
  vhost: /
  username: guest
  password: guest
