# General
date_format_str: '%Y-%m-%d %H:%M:%S.%L'

indexer:
  # the file to which the indexer log is written
  log: 'log/indexer.log'
  # the interval at which the indexer log is rotated
  log_rotation_interval: 'daily'

ssl:
  cert_file: ~
  key_file: ~
  key_pass: ~

workflow:
  logfile: 'log/workflow_service.log'
  shift_age: 'weekly'
  timeout: 60

message_queues: []

fedora_url: 'https://user:password@fedora.example.com:1000/fedora'
solrizer_url: 'https://solr.example.com/solr/collection'
workflow_url: 'https://workflow.example.edu/'

dor_services:
  url: 'http://localhost:3003'
  token: 'not-a-real-token'
