# General
date_format_str: '%Y-%m-%d %H:%M:%S.%L'
rolling_indexer:
  # number of ids to get from Solr in a query
  query_size: 100
  # number of docs to send to Solr in a batch
  batch_size: 5
  # avoid overloading the dor-services-app load balancer (seconds)
  pause_time_between_docs: 0.1
  # a little more than softCommit max time is desired (a Solr 'add' with commitWithin does a softCommit) (seconds)
  # see solrconfig.xml for softCommit max time
  pause_for_solr: 61
  # milliseconds
  commitWithin: 500

ssl:
  cert_file: ~
  key_file: ~
  key_pass: ~

workflow:
  logfile: 'log/workflow_service.log'
  shift_age: 'weekly'
  timeout: 60

solrizer_url: 'https://solr.example.com/solr/collection'
workflow_url: 'https://workflow.example.edu/'

dor_services:
  url: 'http://localhost:3003'
  token: 'not-a-real-token'

rabbitmq:
  hostname: localhost
  vhost: /
  username: guest
  password: guest
