# General
DATE_FORMAT_STR: '%Y-%m-%d %H:%M:%S.%L'

# Content
CONTENT:
  USER: 'user'
  BASE_DIR: '/foo/bar/'
  SERVER_HOST: 'example-bar'
  SDR_SERVER_URL: 'https://sdr.example.com'
  SDR_USER: 'user'
  SDR_PASSWORD: 'password'

# Indexer
INDEXER:
  # the file to which the indexer log is written
  LOG: 'log/indexer.log'
  # the interval at which the indexer log is rotated
  LOG_ROTATION_INTERVAL: 'daily'

# SSL
SSL:
  CERT_FILE: 'cert_name.crt'
  KEY_FILE: 'key_name.key'
  KEY_PASS: 'password'

# Stacks
STACKS:
  DOCUMENT_CACHE_HOST: 'cache.example.com'
  LOCAL_WORKSPACE_ROOT: '/foo/workspace'
  STORAGE_ROOT: '/bar'

# Suri
SURI:
  MINT_IDS: true
  ID_NAMESPACE: 'druid'
  URL: 'https://suri.example.com'
  USER: 'user'
  PASS: 'pass'

# Workflow
WORKFLOW:
  LOGFILE: 'log/workflow_service.log'
  SHIFT_AGE: 'weekly'

MESSAGE_QUEUES: []

# URLs
FEDORA_URL: 'https://user:password@fedora.example.com:1000/fedora'
SOLRIZER_URL: 'https://solr.example.com/solr/collection'
WORKFLOW_URL: 'https://workflow.example.edu/'
